### ISSUE TITLE
Auth Review

### ISSUE THREAD

**Issue by aahmed019** [aahmed019/CampCentral#3]
Hey Justin, I believe my auth is ready for review.

**Comment by jmeyer90** [comment]
Auth Review:

* Auth funtionality starts with our navbar and how we navigate to our auth functionality. The styling of our navbar is included in auth. 
* We can utilize modals instead of page redirects for auth, but the forms should closely resemble what we see on Hipcamp.
* Errors should clear when switching between sign up and login forms.
* When signing up or logging in, the auth modal doesn't leave the page.

**Comment by aahmed019** [comment]
1) Styled a new navbar, removed old logo for design choice.
2) Modals styled to match HipCamp but more edits will be seen at a later time.
3) Errors are completely gone when you switch between login and sign up modals.
4) fixed bug where modal did not leave when a user signed in or signed up.

**Comment by jmeyer90** [comment]
Auth looks great! Feel free to move forward to your next MVP.
